# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: app_profile_index
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800   # 7 jours
                path: /

    access_control:
        # Pages publiques
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

        # Pages protégées
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/score, roles: ROLE_USER }
        - { path: ^/gallery, roles: ROLE_USER }
